# Generated by Django 5.2.3 on 2025-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rent_due_date', models.DateField()),
                ('notify_30_days', models.TimeField(blank=True, null=True)),
                ('notify_60_days', models.TimeField(blank=True, null=True)),
                ('notify_90_days', models.TimeField(blank=True, null=True)),
                ('email_sent_30', models.BooleanField(default=False)),
                ('email_sent_60', models.BooleanField(default=False)),
                ('email_sent_90', models.BooleanField(default=False)),
            ],
        ),
    ]
